// Auth screen
import {default as Welcome} from './WelcomePage'
import {default as Signin} from './registration/SignInForm'
import {default as Signup} from './registration/SignUpForm'
import {default as Forgotpassword} from './registration/ForgotPassword'
import {default as ForgotPassEnterPass} from './registration/ForgotPassEnterPass'
import {default as ForgotPassEnterCode} from './registration/ForgotPassEnterCode'
import {default as ChangePassword} from './registration/ChangePassword'

// Main screen
import {default as Onboarding} from './Onboarding/OnboardingScreen'
import {default as MainNavigation} from './navigation/MainNavigation'
import {default as SearchScreen} from './navigation/firstPage/SearchScreen'
import {default as LoverScreen} from './navigation/firstPage/LoverScreen'
import {default as Home} from './navigation/home/HomeScreen'
import {default as HomePartnerScreen} from './navigation/home/HomePartnerScreen'
import {default as PartnerInfoScreen} from './navigation/booking/PartnerInfoScreen'
import {default as UserScheduleScreen} from './navigation/booking/UserScheduleScreen'
import {default as ScheduleDescription} from './navigation/booking/ScheduleDescription'
import {default as BookingScreen} from './navigation/booking/BookingScreen'
import {default as ChatScreen} from './navigation/chat/ChatScreen'
import {default as ChatListScreen} from './navigation/chat/ChatListScreen'
import {default as EditProfile} from './navigation/setting/EditProfileScreen'
import {default as LanguageScreen} from './navigation/setting/LanguageScreen'
import {default as LocationScreen} from './navigation/setting/LocationScreen'
import {default as PaymentScreen} from './navigation/setting/PaymentScreen'
import {default as ProfileScreen} from './navigation/setting/ProfileScreen'
import {default as SettingNotificationScreen} from './navigation/setting/SettingNotificationScreen'
import {default as NotificationScreen} from './navigation/NotificationScreen'